# Site settings
title: Abinash's blog
email: abinashm89@gmail.com
description: "Do or do not, there is no try - Master Yoda"
baseurl: ""
url: "http://amohant4.github.io"
#twitter_username: 
github_username:  amohant4
linkedin_username: abinashm89
port: 4444

#plugins:
#  - jekyll-seo-tag  

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
