# Site settings
title: Abinash's blog
email: amohant4@asu.edu
description: "Do or do not, there is no try - Master Yoda"
baseurl: ""
url: "http://amohant4.github.io"
#twitter_username: 
github_username:  amohant4
linkedin_username: abinashm89

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge